name: CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        width:
          ref: "11th"
      - run: npm ci
